"""Add recommendation risk lineage columns.

Revision ID: 20260505_0001
Revises: 20260504_0002
Create Date: 2026-05-05
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260505_0001"
down_revision: str | None = "20260504_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_RECOMMENDATION_RISK_COLUMNS = (
    ("risk_snapshot_id", "text", sa.Text()),
    ("portfolio_risk_snapshot_id", "text", sa.Text()),
    ("risk_quality", "text", sa.Text()),
    ("risk_confidence", "double precision", sa.Float()),
    ("risk_score", "double precision", sa.Float()),
    ("risk_level", "text", sa.Text()),
    ("risk_source_status_json", "text", sa.Text()),
    ("risk_bindings_json", "text", sa.Text()),
)


def _upgrade_postgres() -> None:
    for name, ddl, _type in _RECOMMENDATION_RISK_COLUMNS:
        op.execute(f"ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS {name} {ddl}")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS recommendation_risk_bindings (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            recommendation_id integer NOT NULL,
            created_at text NOT NULL,
            ticker text,
            risk_snapshot_id text,
            portfolio_risk_snapshot_id text,
            risk_quality text,
            risk_confidence double precision,
            risk_score double precision,
            risk_level text,
            source_status_json text,
            binding_json text NOT NULL
        )
        """
    )

    for stmt in [
        "CREATE INDEX IF NOT EXISTS idx_recommendations_risk_snapshot ON recommendations(risk_snapshot_id)",
        "CREATE INDEX IF NOT EXISTS idx_recommendations_portfolio_risk_snapshot "
        "ON recommendations(portfolio_risk_snapshot_id)",
        "CREATE INDEX IF NOT EXISTS idx_recommendation_risk_bindings_recommendation "
        "ON recommendation_risk_bindings(recommendation_id)",
        "CREATE INDEX IF NOT EXISTS idx_recommendation_risk_bindings_position "
        "ON recommendation_risk_bindings(risk_snapshot_id)",
        "CREATE INDEX IF NOT EXISTS idx_recommendation_risk_bindings_portfolio "
        "ON recommendation_risk_bindings(portfolio_risk_snapshot_id)",
    ]:
        op.execute(stmt)

    op.execute(
        """
        DO $$
        DECLARE
            sequence_name text;
        BEGIN
            sequence_name := pg_get_serial_sequence('recommendation_risk_bindings', 'id');

            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'talisman_app') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON recommendation_risk_bindings TO talisman_app;
                IF sequence_name IS NOT NULL THEN
                    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO talisman_app', sequence_name);
                END IF;
            END IF;

            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'talisman_worker') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON recommendation_risk_bindings TO talisman_worker;
                IF sequence_name IS NOT NULL THEN
                    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO talisman_worker', sequence_name);
                END IF;
            END IF;
        END $$;
        """
    )


def _upgrade_other() -> None:
    for name, _ddl, column_type in _RECOMMENDATION_RISK_COLUMNS:
        op.add_column("recommendations", sa.Column(name, column_type))

    op.create_table(
        "recommendation_risk_bindings",
        sa.Column("id", sa.Integer, sa.Identity(), primary_key=True),
        sa.Column("recommendation_id", sa.Integer, nullable=False),
        sa.Column("created_at", sa.Text, nullable=False),
        sa.Column("ticker", sa.Text),
        sa.Column("risk_snapshot_id", sa.Text),
        sa.Column("portfolio_risk_snapshot_id", sa.Text),
        sa.Column("risk_quality", sa.Text),
        sa.Column("risk_confidence", sa.Float),
        sa.Column("risk_score", sa.Float),
        sa.Column("risk_level", sa.Text),
        sa.Column("source_status_json", sa.Text),
        sa.Column("binding_json", sa.Text, nullable=False),
    )
    op.create_index("idx_recommendations_risk_snapshot", "recommendations", ["risk_snapshot_id"])
    op.create_index(
        "idx_recommendations_portfolio_risk_snapshot",
        "recommendations",
        ["portfolio_risk_snapshot_id"],
    )
    op.create_index(
        "idx_recommendation_risk_bindings_recommendation",
        "recommendation_risk_bindings",
        ["recommendation_id"],
    )
    op.create_index(
        "idx_recommendation_risk_bindings_position",
        "recommendation_risk_bindings",
        ["risk_snapshot_id"],
    )
    op.create_index(
        "idx_recommendation_risk_bindings_portfolio",
        "recommendation_risk_bindings",
        ["portfolio_risk_snapshot_id"],
    )


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _upgrade_postgres()
        return
    _upgrade_other()


def downgrade() -> None:
    for index in [
        "idx_recommendation_risk_bindings_portfolio",
        "idx_recommendation_risk_bindings_position",
        "idx_recommendation_risk_bindings_recommendation",
        "idx_recommendations_portfolio_risk_snapshot",
        "idx_recommendations_risk_snapshot",
    ]:
        op.execute(f"DROP INDEX IF EXISTS {index}")
    op.drop_table("recommendation_risk_bindings")
    for name, _ddl, _type in reversed(_RECOMMENDATION_RISK_COLUMNS):
        op.execute(f"ALTER TABLE recommendations DROP COLUMN IF EXISTS {name}")
