"""Add governance outbox and critical lineage metadata.

Revision ID: 20260503_0012
Revises: 20260503_0011
Create Date: 2026-05-03
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "20260503_0012"
down_revision: str | None = "20260503_0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _ensure_policy_gate_results() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS policy_gate_results (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at text NOT NULL,
            decision text NOT NULL
                CHECK (decision IN ('pass', 'warn', 'review_required', 'blocked', 'error')),
            review_required integer NOT NULL DEFAULT 0,
            override_acknowledged integer NOT NULL DEFAULT 0,
            account_id text,
            portfolio_id text,
            policy_id text,
            action_id text,
            source_type text,
            source_id text,
            target_type text,
            target_id text,
            payload_hash text,
            provenance_event_id text,
            lineage_root_id text,
            lineage_completeness text NOT NULL DEFAULT 'legacy_partial',
            result_json text NOT NULL
        )
        """
    )


def upgrade() -> None:
    _ensure_policy_gate_results()

    for stmt in [
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS criticality text NOT NULL DEFAULT 'operational'",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS idempotency_key text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS producer_name text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS producer_version text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS redaction_policy text NOT NULL DEFAULT 'audit_summary_v1'",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS retention_class text NOT NULL DEFAULT 'audit_365d'",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS criticality text NOT NULL DEFAULT 'operational'",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS idempotency_key text",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS producer_name text",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS producer_version text",
        "ALTER TABLE provenance_links ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS provenance_event_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS lineage_completeness text NOT NULL DEFAULT 'legacy_partial'",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_gate_result_id integer",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_gate_status text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_gate_decision text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_gate_review_required integer NOT NULL DEFAULT 0",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_gate_failures_json text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_gate_warnings_json text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_gate_disclosures_json text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS account_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS portfolio_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS policy_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS trade_proposal_json text",
        "ALTER TABLE policy_gate_results ADD COLUMN IF NOT EXISTS provenance_event_id text",
        "ALTER TABLE policy_gate_results ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE policy_gate_results ADD COLUMN IF NOT EXISTS lineage_completeness text NOT NULL DEFAULT 'legacy_partial'",
    ]:
        op.execute(stmt)

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS governance_outbox (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idempotency_key text NOT NULL UNIQUE,
            event_bundle_json text NOT NULL,
            status text NOT NULL DEFAULT 'pending',
            attempt_count integer NOT NULL DEFAULT 0,
            next_attempt_at text NOT NULL,
            locked_at text,
            last_error text,
            dead_lettered_at text,
            lineage_root_id text,
            retention_class text NOT NULL DEFAULT 'financial_lineage_7y',
            created_at text NOT NULL,
            updated_at text NOT NULL
        )
        """
    )
    for stmt in [
        "CREATE INDEX IF NOT EXISTS idx_audit_events_lineage_root ON audit_events(lineage_root_id, occurred_at)",
        "CREATE INDEX IF NOT EXISTS idx_audit_events_criticality_time ON audit_events(criticality, occurred_at)",
        "CREATE INDEX IF NOT EXISTS idx_audit_events_idempotency ON audit_events(idempotency_key)",
        "CREATE INDEX IF NOT EXISTS idx_provenance_events_lineage_root ON provenance_events(lineage_root_id, started_at)",
        "CREATE INDEX IF NOT EXISTS idx_provenance_events_idempotency ON provenance_events(idempotency_key)",
        "CREATE INDEX IF NOT EXISTS idx_provenance_links_lineage_root ON provenance_links(lineage_root_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_recommendations_lineage_root ON recommendations(lineage_root_id)",
        "CREATE INDEX IF NOT EXISTS idx_recommendations_lineage_completeness ON recommendations(lineage_completeness)",
        "CREATE INDEX IF NOT EXISTS idx_recommendations_policy_gate ON recommendations(policy_gate_decision)",
        "CREATE INDEX IF NOT EXISTS idx_policy_gate_results_decision ON policy_gate_results(decision, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_policy_gate_results_target ON policy_gate_results(target_type, target_id)",
        "CREATE INDEX IF NOT EXISTS idx_policy_gate_results_action ON policy_gate_results(action_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_policy_gate_results_lineage_root ON policy_gate_results(lineage_root_id)",
        "CREATE INDEX IF NOT EXISTS idx_governance_outbox_status_next ON governance_outbox(status, next_attempt_at)",
        "CREATE INDEX IF NOT EXISTS idx_governance_outbox_lineage_root ON governance_outbox(lineage_root_id)",
        "CREATE INDEX IF NOT EXISTS idx_governance_outbox_dead_letter ON governance_outbox(dead_lettered_at)",
    ]:
        op.execute(stmt)

    op.execute(
        "UPDATE recommendations SET lineage_completeness = 'legacy_partial' "
        "WHERE lineage_completeness IS NULL OR lineage_completeness = ''"
    )
    op.execute(
        "UPDATE policy_gate_results SET lineage_completeness = 'legacy_partial' "
        "WHERE lineage_completeness IS NULL OR lineage_completeness = ''"
    )


def downgrade() -> None:
    for stmt in [
        "DROP INDEX IF EXISTS idx_governance_outbox_dead_letter",
        "DROP INDEX IF EXISTS idx_governance_outbox_lineage_root",
        "DROP INDEX IF EXISTS idx_governance_outbox_status_next",
        "DROP INDEX IF EXISTS idx_policy_gate_results_lineage_root",
        "DROP INDEX IF EXISTS idx_policy_gate_results_action",
        "DROP INDEX IF EXISTS idx_policy_gate_results_target",
        "DROP INDEX IF EXISTS idx_policy_gate_results_decision",
        "DROP INDEX IF EXISTS idx_recommendations_policy_gate",
        "DROP INDEX IF EXISTS idx_recommendations_lineage_completeness",
        "DROP INDEX IF EXISTS idx_recommendations_lineage_root",
        "DROP INDEX IF EXISTS idx_provenance_links_lineage_root",
        "DROP INDEX IF EXISTS idx_provenance_events_idempotency",
        "DROP INDEX IF EXISTS idx_provenance_events_lineage_root",
        "DROP INDEX IF EXISTS idx_audit_events_idempotency",
        "DROP INDEX IF EXISTS idx_audit_events_criticality_time",
        "DROP INDEX IF EXISTS idx_audit_events_lineage_root",
    ]:
        op.execute(stmt)
    op.execute("DROP TABLE IF EXISTS governance_outbox")
    for stmt in [
        "ALTER TABLE policy_gate_results DROP COLUMN IF EXISTS lineage_completeness",
        "ALTER TABLE policy_gate_results DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE policy_gate_results DROP COLUMN IF EXISTS provenance_event_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS trade_proposal_json",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS portfolio_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS account_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_gate_disclosures_json",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_gate_warnings_json",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_gate_failures_json",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_gate_review_required",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_gate_decision",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_gate_status",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS policy_gate_result_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS lineage_completeness",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS provenance_event_id",
        "ALTER TABLE provenance_links DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS producer_version",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS producer_name",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS idempotency_key",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS criticality",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS schema_version",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS retention_class",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS redaction_policy",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS producer_version",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS producer_name",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS idempotency_key",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS criticality",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS schema_version",
    ]:
        op.execute(stmt)
