"""Add governance outbox and critical lineage metadata.

Revision ID: 20260503_0012
Revises: 20260503_0011
Create Date: 2026-05-03
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "20260503_0012"
down_revision: str | None = "20260503_0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for stmt in [
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS criticality text NOT NULL DEFAULT 'operational'",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS idempotency_key text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS producer_name text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS producer_version text",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS redaction_policy text NOT NULL DEFAULT 'audit_summary_v1'",
        "ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS retention_class text NOT NULL DEFAULT 'audit_365d'",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS criticality text NOT NULL DEFAULT 'operational'",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS idempotency_key text",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS producer_name text",
        "ALTER TABLE provenance_events ADD COLUMN IF NOT EXISTS producer_version text",
        "ALTER TABLE provenance_links ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS provenance_event_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS lineage_completeness text NOT NULL DEFAULT 'legacy_partial'",
        "ALTER TABLE policy_gate_results ADD COLUMN IF NOT EXISTS provenance_event_id text",
        "ALTER TABLE policy_gate_results ADD COLUMN IF NOT EXISTS lineage_root_id text",
        "ALTER TABLE policy_gate_results ADD COLUMN IF NOT EXISTS lineage_completeness text NOT NULL DEFAULT 'legacy_partial'",
    ]:
        op.execute(stmt)

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS governance_outbox (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idempotency_key text NOT NULL UNIQUE,
            event_bundle_json text NOT NULL,
            status text NOT NULL DEFAULT 'pending',
            attempt_count integer NOT NULL DEFAULT 0,
            next_attempt_at text NOT NULL,
            locked_at text,
            last_error text,
            dead_lettered_at text,
            lineage_root_id text,
            retention_class text NOT NULL DEFAULT 'financial_lineage_7y',
            created_at text NOT NULL,
            updated_at text NOT NULL
        )
        """
    )
    for stmt in [
        "CREATE INDEX IF NOT EXISTS idx_audit_events_lineage_root ON audit_events(lineage_root_id, occurred_at)",
        "CREATE INDEX IF NOT EXISTS idx_audit_events_criticality_time ON audit_events(criticality, occurred_at)",
        "CREATE INDEX IF NOT EXISTS idx_audit_events_idempotency ON audit_events(idempotency_key)",
        "CREATE INDEX IF NOT EXISTS idx_provenance_events_lineage_root ON provenance_events(lineage_root_id, started_at)",
        "CREATE INDEX IF NOT EXISTS idx_provenance_events_idempotency ON provenance_events(idempotency_key)",
        "CREATE INDEX IF NOT EXISTS idx_provenance_links_lineage_root ON provenance_links(lineage_root_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_recommendations_lineage_root ON recommendations(lineage_root_id)",
        "CREATE INDEX IF NOT EXISTS idx_recommendations_lineage_completeness ON recommendations(lineage_completeness)",
        "CREATE INDEX IF NOT EXISTS idx_policy_gate_results_lineage_root ON policy_gate_results(lineage_root_id)",
        "CREATE INDEX IF NOT EXISTS idx_governance_outbox_status_next ON governance_outbox(status, next_attempt_at)",
        "CREATE INDEX IF NOT EXISTS idx_governance_outbox_lineage_root ON governance_outbox(lineage_root_id)",
        "CREATE INDEX IF NOT EXISTS idx_governance_outbox_dead_letter ON governance_outbox(dead_lettered_at)",
    ]:
        op.execute(stmt)

    op.execute(
        "UPDATE recommendations SET lineage_completeness = 'legacy_partial' "
        "WHERE lineage_completeness IS NULL OR lineage_completeness = ''"
    )
    op.execute(
        "UPDATE policy_gate_results SET lineage_completeness = 'legacy_partial' "
        "WHERE lineage_completeness IS NULL OR lineage_completeness = ''"
    )


def downgrade() -> None:
    for stmt in [
        "DROP INDEX IF EXISTS idx_governance_outbox_dead_letter",
        "DROP INDEX IF EXISTS idx_governance_outbox_lineage_root",
        "DROP INDEX IF EXISTS idx_governance_outbox_status_next",
        "DROP INDEX IF EXISTS idx_policy_gate_results_lineage_root",
        "DROP INDEX IF EXISTS idx_recommendations_lineage_completeness",
        "DROP INDEX IF EXISTS idx_recommendations_lineage_root",
        "DROP INDEX IF EXISTS idx_provenance_links_lineage_root",
        "DROP INDEX IF EXISTS idx_provenance_events_idempotency",
        "DROP INDEX IF EXISTS idx_provenance_events_lineage_root",
        "DROP INDEX IF EXISTS idx_audit_events_idempotency",
        "DROP INDEX IF EXISTS idx_audit_events_criticality_time",
        "DROP INDEX IF EXISTS idx_audit_events_lineage_root",
    ]:
        op.execute(stmt)
    op.execute("DROP TABLE IF EXISTS governance_outbox")
    for stmt in [
        "ALTER TABLE policy_gate_results DROP COLUMN IF EXISTS lineage_completeness",
        "ALTER TABLE policy_gate_results DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE policy_gate_results DROP COLUMN IF EXISTS provenance_event_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS lineage_completeness",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE recommendations DROP COLUMN IF EXISTS provenance_event_id",
        "ALTER TABLE provenance_links DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS producer_version",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS producer_name",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS idempotency_key",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS criticality",
        "ALTER TABLE provenance_events DROP COLUMN IF EXISTS schema_version",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS retention_class",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS redaction_policy",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS producer_version",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS producer_name",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS idempotency_key",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS lineage_root_id",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS criticality",
        "ALTER TABLE audit_events DROP COLUMN IF EXISTS schema_version",
    ]:
        op.execute(stmt)
