"""Add resolved state to optimization alerts.

Revision ID: 20260509_0001
Revises: 20260507_0001
Create Date: 2026-05-09
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260509_0001"
down_revision: str | None = "20260507_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SQLITE_OPTIMIZATION_ALERTS_WITH_RESOLVED = """
CREATE TABLE optimization_alerts (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    mission_id               INTEGER NOT NULL,
    run_id                   TEXT NOT NULL,
    ticker                   TEXT,
    alert_type               TEXT NOT NULL,
    severity                 TEXT NOT NULL
                             CHECK (severity IN ('low', 'normal', 'high', 'urgent')),
    status                   TEXT NOT NULL DEFAULT 'open'
                             CHECK (status IN ('open', 'dismissed', 'superseded', 'resolved')),
    previous_snapshot_id     INTEGER,
    current_snapshot_id      INTEGER,
    change_summary           TEXT NOT NULL,
    evidence_json            TEXT,
    approval_id              INTEGER,
    recommendation_id        INTEGER,
    action_item_approval_id  INTEGER,
    created_at               TEXT NOT NULL,
    dismissed_at             TEXT,
    dismissed_note           TEXT,
    resolved_at              TEXT,
    resolved_reason          TEXT
)
"""

SQLITE_OPTIMIZATION_ALERTS_LEGACY = """
CREATE TABLE optimization_alerts (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    mission_id               INTEGER NOT NULL,
    run_id                   TEXT NOT NULL,
    ticker                   TEXT,
    alert_type               TEXT NOT NULL,
    severity                 TEXT NOT NULL
                             CHECK (severity IN ('low', 'normal', 'high', 'urgent')),
    status                   TEXT NOT NULL DEFAULT 'open'
                             CHECK (status IN ('open', 'dismissed', 'superseded')),
    previous_snapshot_id     INTEGER,
    current_snapshot_id      INTEGER,
    change_summary           TEXT NOT NULL,
    evidence_json            TEXT,
    approval_id              INTEGER,
    recommendation_id        INTEGER,
    action_item_approval_id  INTEGER,
    created_at               TEXT NOT NULL,
    dismissed_at             TEXT,
    dismissed_note           TEXT
)
"""


def _sqlite_columns(table: str) -> set[str]:
    bind = op.get_bind()
    return {str(row[1]) for row in bind.execute(sa.text(f"PRAGMA table_info({table})")).fetchall()}


def _table_exists(table: str) -> bool:
    return bool(sa.inspect(op.get_bind()).has_table(table))


def _create_postgres_optimization_tables() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS optimization_missions (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL UNIQUE,
            status text NOT NULL DEFAULT 'active'
                CONSTRAINT optimization_missions_status_check
                CHECK (status IN ('active', 'paused', 'retired')),
            schedule_label text,
            scenario_json text,
            source_config_json text,
            thresholds_json text,
            created_at text NOT NULL,
            updated_at text NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS optimization_runs (
            run_id text PRIMARY KEY,
            mission_id integer NOT NULL,
            mission_name text NOT NULL,
            status text NOT NULL DEFAULT 'running'
                CONSTRAINT optimization_runs_status_check
                CHECK (status IN ('running', 'completed', 'failed')),
            started_at text NOT NULL,
            completed_at text,
            input_hash text,
            output_hash text,
            summary_json text,
            source_freshness_json text,
            error text
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS optimization_action_snapshots (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id text NOT NULL,
            mission_id integer NOT NULL,
            ticker text,
            asset text,
            direction text,
            action text NOT NULL,
            conviction_band text,
            priority_score double precision,
            confidence double precision,
            gate_status text,
            severity text,
            state_hash text NOT NULL,
            evidence_json text,
            source_links_json text,
            created_at text NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS optimization_alerts (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mission_id integer NOT NULL,
            run_id text NOT NULL,
            ticker text,
            alert_type text NOT NULL,
            severity text NOT NULL
                CONSTRAINT optimization_alerts_severity_check
                CHECK (severity IN ('low', 'normal', 'high', 'urgent')),
            status text NOT NULL DEFAULT 'open'
                CONSTRAINT optimization_alerts_status_check
                CHECK (status IN ('open', 'dismissed', 'superseded', 'resolved')),
            previous_snapshot_id integer,
            current_snapshot_id integer,
            change_summary text NOT NULL,
            evidence_json text,
            approval_id integer,
            recommendation_id integer,
            action_item_approval_id integer,
            created_at text NOT NULL,
            dismissed_at text,
            dismissed_note text,
            resolved_at text,
            resolved_reason text
        )
        """
    )
    for statement in [
        "CREATE INDEX IF NOT EXISTS idx_optimization_missions_status ON optimization_missions(status)",
        (
            "CREATE INDEX IF NOT EXISTS idx_optimization_runs_mission_started "
            "ON optimization_runs(mission_id, started_at DESC)"
        ),
        "CREATE INDEX IF NOT EXISTS idx_optimization_runs_status ON optimization_runs(status)",
        "CREATE INDEX IF NOT EXISTS idx_optimization_snapshots_run ON optimization_action_snapshots(run_id)",
        (
            "CREATE INDEX IF NOT EXISTS idx_optimization_snapshots_mission_ticker "
            "ON optimization_action_snapshots(mission_id, ticker)"
        ),
        "CREATE INDEX IF NOT EXISTS idx_optimization_snapshots_hash ON optimization_action_snapshots(state_hash)",
        "CREATE INDEX IF NOT EXISTS idx_optimization_alerts_status ON optimization_alerts(status, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_optimization_alerts_mission ON optimization_alerts(mission_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_optimization_alerts_ticker ON optimization_alerts(ticker)",
    ]:
        op.execute(statement)


def _grant_postgres_optimization_tables() -> None:
    op.execute(
        """
        DO $$
        DECLARE
            target_table text;
            sequence_name text;
        BEGIN
            FOREACH target_table IN ARRAY ARRAY[
                'optimization_missions',
                'optimization_runs',
                'optimization_action_snapshots',
                'optimization_alerts'
            ]
            LOOP
                sequence_name := NULL;
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = target_table
                      AND column_name = 'id'
                ) THEN
                    sequence_name := pg_get_serial_sequence(target_table, 'id');
                END IF;

                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'talisman_app') THEN
                    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO talisman_app', target_table);
                    IF sequence_name IS NOT NULL THEN
                        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO talisman_app', sequence_name);
                    END IF;
                END IF;

                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'talisman_worker') THEN
                    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO talisman_worker', target_table);
                    IF sequence_name IS NOT NULL THEN
                        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO talisman_worker', sequence_name);
                    END IF;
                END IF;
            END LOOP;
        END $$;
        """
    )


def _recreate_sqlite_optimization_alerts(*, include_resolved: bool) -> None:
    legacy_table = "optimization_alerts_status_upgrade_old"
    op.execute(f"DROP TABLE IF EXISTS {legacy_table}")
    if not include_resolved:
        op.execute("UPDATE optimization_alerts SET status = 'superseded' WHERE status = 'resolved'")
    op.execute(f"ALTER TABLE optimization_alerts RENAME TO {legacy_table}")
    op.execute(SQLITE_OPTIMIZATION_ALERTS_WITH_RESOLVED if include_resolved else SQLITE_OPTIMIZATION_ALERTS_LEGACY)

    legacy_cols = _sqlite_columns(legacy_table)
    target_cols = _sqlite_columns("optimization_alerts")
    copy_cols = [col for col in target_cols if col in legacy_cols]
    cols_sql = ", ".join(copy_cols)
    if cols_sql:
        op.execute(f"INSERT INTO optimization_alerts ({cols_sql}) SELECT {cols_sql} FROM {legacy_table}")
    op.execute(f"DROP TABLE {legacy_table}")


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _create_postgres_optimization_tables()
        op.execute("ALTER TABLE optimization_alerts ADD COLUMN IF NOT EXISTS resolved_at TEXT")
        op.execute("ALTER TABLE optimization_alerts ADD COLUMN IF NOT EXISTS resolved_reason TEXT")
        op.execute("ALTER TABLE optimization_alerts DROP CONSTRAINT IF EXISTS optimization_alerts_status_check")
        op.execute(
            """
            ALTER TABLE optimization_alerts
            ADD CONSTRAINT optimization_alerts_status_check
            CHECK (status IN ('open', 'dismissed', 'superseded', 'resolved'))
            """
        )
        _grant_postgres_optimization_tables()
        return

    if not _table_exists("optimization_alerts"):
        op.execute(SQLITE_OPTIMIZATION_ALERTS_WITH_RESOLVED)
        return
    _recreate_sqlite_optimization_alerts(include_resolved=True)


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        if not _table_exists("optimization_alerts"):
            return
        op.execute("UPDATE optimization_alerts SET status = 'superseded' WHERE status = 'resolved'")
        op.execute("ALTER TABLE optimization_alerts DROP CONSTRAINT IF EXISTS optimization_alerts_status_check")
        op.execute(
            """
            ALTER TABLE optimization_alerts
            ADD CONSTRAINT optimization_alerts_status_check
            CHECK (status IN ('open', 'dismissed', 'superseded'))
            """
        )
        op.execute("ALTER TABLE optimization_alerts DROP COLUMN IF EXISTS resolved_reason")
        op.execute("ALTER TABLE optimization_alerts DROP COLUMN IF EXISTS resolved_at")
        return

    if not _table_exists("optimization_alerts"):
        return
    _recreate_sqlite_optimization_alerts(include_resolved=False)
