"""Add schema definition registry and ontology relation versions.

Revision ID: 20260503_0006
Revises: 20260503_0005
Create Date: 2026-05-03
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260503_0006"
down_revision: str | None = "20260503_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS action_runs (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action_id text NOT NULL,
            action_schema_version integer NOT NULL DEFAULT 1,
            actor_type text NOT NULL,
            actor_id text,
            source_type text,
            source_id text,
            approval_id integer,
            parent_action_run_id integer,
            input_hash text,
            input_json text,
            output_json text,
            status text NOT NULL DEFAULT 'running',
            error text,
            started_at text NOT NULL,
            completed_at text
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS action_events (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action_run_id integer NOT NULL,
            event_type text NOT NULL,
            message text,
            payload_json text,
            created_at text NOT NULL
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_action_runs_action_id ON action_runs(action_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_action_runs_status ON action_runs(status)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_action_runs_approval ON action_runs(approval_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_action_events_run ON action_events(action_run_id)")
    op.create_table(
        "schema_definitions",
        sa.Column("schema_kind", sa.Text, nullable=False),
        sa.Column("schema_name", sa.Text, nullable=False),
        sa.Column("schema_version", sa.Integer, nullable=False),
        sa.Column("definition_json", sa.Text, nullable=False),
        sa.Column("definition_hash", sa.Text, nullable=False),
        sa.Column("compatibility_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.Text, nullable=False, server_default="active"),
        sa.Column("created_at", sa.Text, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP::text")),
        sa.Column("deprecated_at", sa.Text),
        sa.PrimaryKeyConstraint("schema_kind", "schema_name", "schema_version"),
    )
    op.create_index("idx_schema_definitions_kind_status", "schema_definitions", ["schema_kind", "status"])

    for table_name in ("ontology_edges", "ontology_snapshot_edges"):
        op.execute(
            f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS relation_schema_name text NOT NULL DEFAULT 'legacy'"
        )
        op.execute(
            f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS relation_schema_version integer NOT NULL DEFAULT 0"
        )

    op.create_table(
        "ontology_run_schema_bindings",
        sa.Column("run_id", sa.Text, sa.ForeignKey("ontology_runs.run_id", ondelete="CASCADE"), nullable=False),
        sa.Column("schema_kind", sa.Text, nullable=False),
        sa.Column("schema_name", sa.Text, nullable=False),
        sa.Column("schema_version", sa.Integer, nullable=False),
        sa.Column("definition_hash", sa.Text, nullable=False),
        sa.PrimaryKeyConstraint("run_id", "schema_kind", "schema_name", "schema_version"),
    )
    op.create_index(
        "idx_ontology_run_schema_bindings_run",
        "ontology_run_schema_bindings",
        ["run_id"],
    )

    for table_name in ("pending_approvals", "action_runs"):
        op.execute(f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS action_schema_name text")
        op.execute(f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS request_schema_name text")
        op.execute(f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS request_schema_version integer")

    op.execute("ALTER TABLE async_jobs ADD COLUMN IF NOT EXISTS request_schema_name text")
    op.execute("ALTER TABLE async_jobs ADD COLUMN IF NOT EXISTS request_schema_version integer")


def downgrade() -> None:
    op.drop_column("async_jobs", "request_schema_version")
    op.drop_column("async_jobs", "request_schema_name")

    for table_name in ("action_runs", "pending_approvals"):
        op.drop_column(table_name, "request_schema_version")
        op.drop_column(table_name, "request_schema_name")
        op.drop_column(table_name, "action_schema_name")

    op.drop_index("idx_ontology_run_schema_bindings_run", table_name="ontology_run_schema_bindings")
    op.drop_table("ontology_run_schema_bindings")

    for table_name in ("ontology_snapshot_edges", "ontology_edges"):
        op.drop_column(table_name, "relation_schema_version")
        op.drop_column(table_name, "relation_schema_name")

    op.drop_index("idx_schema_definitions_kind_status", table_name="schema_definitions")
    op.drop_table("schema_definitions")
