from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

EntityType = Literal[
    "Asset",
    "Instrument",
    "Issuer",
    "Investor",
    "Account",
    "Portfolio",
    "InvestmentPolicy",
    "RiskLimit",
    "RiskMetric",
    "Scenario",
    "PolicyGateResult",
    "TradeProposal",
    "SourceRecord",
    "ObjectVersionRef",
    "ExecutedAction",
    "ExecutedDecisionRecord",
    "AuditEvent",
    "Sector",
    "MacroIndicator",
    "Signal",
    "Position",
    "HedgePosition",
    "Thesis",
    "Evaluation",
    "Catalyst",
    "KillCondition",
    "ThesisClaim",
    "Evidence",
    "Citation",
    "ActionItem",
    "WatchTrigger",
    "Approval",
    "ActionRun",
    "ActionEvent",
    "ProvenanceEvent",
    "RelationVersionRef",
    "SchemaDefinitionRef",
    "OntologyRunRef",
    "AgentSessionRef",
    "ModelCallRef",
    "ToolCallRef",
    "ComputedSnapshotRef",
    "MarketRegimeSnapshot",
    "SignalFactorScore",
    "ForwardOutlook",
    "RegimeEpisode",
    "PositionRiskSnapshot",
    "PortfolioRiskSnapshot",
    "WorkflowRun",
    "WorkflowArtifact",
    "Recommendation",
    "ReportRun",
    "SourceManifest",
    "DocumentArtifact",
    "MediaArtifact",
    "ExtractionRun",
    "Observation",
    "Classification",
    "PatternDetection",
    "AnalystFeedback",
    "EquityOverview",
    "CompanyFinancialProfile",
    "ExtrinsicSensitivity",
    "IndustryForceAssessment",
    "SupplyDemandOutlook",
    "SupplyChainRelationship",
    "ThesisDocument",
    "ThesisSection",
    "InvestmentIdea",
    "IdeaEvaluation",
    "IdeaComparisonRun",
    "IdeaComparisonRanking",
    "FactorScore",
    "MissingInformationRequirement",
    "OptimizationMission",
    "OptimizationRun",
    "OptimizationActionSnapshot",
    "OptimizationAlert",
    "SourceFreshness",
    "ManagementQualityAssessment",
    "ManagementQualityScorecardRow",
    "ManagementQualityAccomplishment",
    "ManagementQualitySetback",
]
RelationType = Literal[
    "references_asset",
    "portfolio_holds_position",
    "position_references_instrument",
    "instrument_issued_by_issuer",
    "thesis_covers_instrument",
    "claim_supported_by_evidence",
    "claim_disconfirmed_by_evidence",
    "evidence_has_citation",
    "belongs_to_sector",
    "has_thesis",
    "evaluated_by",
    "has_catalyst",
    "emits_signal",
    "affected_by",
    "exposed_to_signal",
    "position_has_hedge",
    "thesis_has_kill_condition",
    "thesis_has_claim",
    "claim_links_catalyst",
    "claim_links_kill_condition",
    "action_item_targets_object",
    "watch_trigger_targets_object",
    "approval_proposes_action",
    "approval_applies_action_run",
    "action_run_mutates_object_version",
    "workflow_run_produces_artifact",
    "report_run_produces_recommendation",
    "workflow_artifact_proposes_approval",
    "source_record_materializes_object",
    "recommendation_supported_by_source_record",
    "recommendation_uses_risk_metric",
    "recommendation_uses_scenario",
    "trade_proposal_targets_asset",
    "trade_proposal_requires_approval",
    "approval_targets_recommendation",
    "approval_targets_trade_proposal",
    "approval_targets_workflow_artifact",
    "action_run_produces_executed_action",
    "executed_action_mutates_object_version",
    "source_record_materializes_object_version",
    "audit_event_observes_action_run",
    "investor_owns_account",
    "account_has_portfolio",
    "account_governed_by_policy",
    "policy_has_risk_limit",
    "recommendation_targets_account",
    "recommendation_targets_portfolio",
    "recommendation_targets_instrument",
    "trade_proposal_derives_from_recommendation",
    "approval_targets_research_object",
    "executed_decision_applies_approval",
    "executed_decision_records_action_run",
    "policy_gate_evaluates_recommendation",
    "policy_gate_evaluates_trade_proposal",
    "policy_gate_uses_risk_metric",
    "policy_gate_uses_scenario",
    "provenance_used",
    "provenance_produced",
    "provenance_schema_bound",
    "provenance_executed",
    "provenance_executed_as",
    "provenance_triggered",
    "provenance_proposed",
    "provenance_resolved_by",
    "provenance_approved_execution",
    "provenance_audited_by",
    "provenance_updated",
    "idea_has_evaluation",
    "comparison_run_has_ranking",
    "ranking_targets_idea",
    "ranking_uses_evaluation",
    "research_object_has_factor_score",
    "research_object_has_missing_information",
    "research_object_supported_by_evidence",
    "research_object_disconfirmed_by_evidence",
    "research_object_uses_document",
    "research_object_links_recommendation",
    "research_object_links_approval",
    "research_object_links_action_item",
    "management_quality_assesses_issuer",
    "management_quality_has_scorecard_row",
    "management_quality_has_accomplishment",
    "management_quality_has_setback",
    "optimization_mission_has_run",
    "optimization_run_has_snapshot",
    "optimization_alert_current_snapshot",
    "optimization_alert_previous_snapshot",
    "optimization_snapshot_targets_position",
    "optimization_snapshot_targets_instrument",
    "optimization_alert_links_approval",
    "optimization_alert_links_action_item",
    "optimization_object_has_source_freshness",
    "computed_snapshot_materializes_object_version",
    "market_regime_has_factor_score",
    "market_regime_has_forward_outlook",
    "market_regime_has_episode",
    "factor_score_uses_source_record",
    "factor_score_uses_computed_snapshot",
    "market_regime_uses_risk_snapshot",
    "market_regime_references_macro_indicator",
    "factor_score_references_sector",
    "recommendation_supported_by_evidence",
    "recommendation_contradicted_by_evidence",
    "evidence_cites_citation",
    "recommendation_has_policy_gate_result",
    "recommendation_has_trade_proposal",
    "recommendation_uses_position_risk_snapshot",
    "recommendation_uses_portfolio_risk_snapshot",
    "document_artifact_materializes_research_object",
    "source_manifest_governs_source_record",
    "source_record_produces_document_artifact",
    "source_record_produces_media_artifact",
    "artifact_has_extraction_run",
    "extraction_run_produces_observation",
    "extraction_run_produces_classification",
    "extraction_run_produces_pattern_detection",
    "analyst_feedback_targets_object",
    "equity_overview_covers_issuer",
    "equity_overview_covers_instrument",
    "equity_overview_has_financial_profile",
    "equity_overview_has_extrinsic_sensitivity",
    "equity_overview_has_industry_force",
    "equity_overview_has_supply_demand_outlook",
    "equity_overview_has_supply_chain_relationship",
    "thesis_document_covers_issuer",
    "thesis_document_covers_instrument",
    "thesis_document_has_section",
]
ParserSource = Literal["structured", "llm", "deterministic_fallback"]


@dataclass(slots=True)
class OntologyNode:
    id: str
    type: EntityType
    label: str
    properties: dict[str, Any] = field(default_factory=dict)
    schema_name: str = "canonical"
    schema_version: int = 1


@dataclass(slots=True)
class OntologyEdge:
    source_id: str
    target_id: str
    relation_type: RelationType
    properties: dict[str, Any] = field(default_factory=dict)
    schema_name: str = "canonical"
    schema_version: int = 1
    relation_schema_name: str = "canonical"
    relation_schema_version: int = 1


@dataclass(slots=True)
class InterpretedQuery:
    intent: str
    source: ParserSource
    filters: dict[str, Any] = field(default_factory=dict)
    entity: str | None = None
    original_query: str | None = None
