"""Backward-compatible proactive alert gate wrapper around the shared contract."""

from decision_quality.scout_skeptic_sizer_gate import (
    HIGH_STAKES_ACTION_TYPES,
    MONITOR_DOWNGRADE_ACTION_TYPES,
    WORKFLOW_SOURCE_TYPES,
    GateStatus,
    PassArtifact,
    PassStatus,
    ProactiveAlertGateResult,
    ScoutPassArtifact,
    ScoutSkepticSizerGateResult,
    SizerPassArtifact,
    SkepticPassArtifact,
    apply_proactive_alert_gate,
    apply_recommendation_scout_skeptic_sizer_gate,
    build_chat_scout_skeptic_sizer_gate,
    evaluate_proactive_alert_gate,
    evaluate_scout_skeptic_sizer_gate,
    is_high_stakes_action_item,
    proactive_alert_gate_enabled,
    proactive_alert_llm_passes_enabled,
    scout_skeptic_sizer_gate_enabled,
    should_apply_proactive_alert_gate,
    should_apply_recommendation_gate,
)

__all__ = [
    "HIGH_STAKES_ACTION_TYPES",
    "MONITOR_DOWNGRADE_ACTION_TYPES",
    "PassArtifact",
    "PassStatus",
    "GateStatus",
    "ProactiveAlertGateResult",
    "ScoutPassArtifact",
    "ScoutSkepticSizerGateResult",
    "SizerPassArtifact",
    "SkepticPassArtifact",
    "WORKFLOW_SOURCE_TYPES",
    "apply_proactive_alert_gate",
    "apply_recommendation_scout_skeptic_sizer_gate",
    "build_chat_scout_skeptic_sizer_gate",
    "evaluate_proactive_alert_gate",
    "evaluate_scout_skeptic_sizer_gate",
    "is_high_stakes_action_item",
    "proactive_alert_gate_enabled",
    "proactive_alert_llm_passes_enabled",
    "scout_skeptic_sizer_gate_enabled",
    "should_apply_proactive_alert_gate",
    "should_apply_recommendation_gate",
]
